# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'informacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_informacion(object):
    def setupUi(self, informacion):
        informacion.setObjectName("informacion")
        informacion.resize(424, 206)
        self.label = QtWidgets.QLabel(informacion)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 71))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(informacion)
        self.label_2.setGeometry(QtCore.QRect(140, 60, 261, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(informacion)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 241, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(informacion)
        self.label_4.setGeometry(QtCore.QRect(200, 130, 171, 51))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(informacion)
        QtCore.QMetaObject.connectSlotsByName(informacion)

    def retranslateUi(self, informacion):
        _translate = QtCore.QCoreApplication.translate
        informacion.setWindowTitle(_translate("informacion", "Informacion "))
        self.label.setText(_translate("informacion", "Sistema desarrollado por: Ana Inés Kessler, Gustavo keimel Alex Menéndez"))
        self.label_2.setText(_translate("informacion", "Benjamin Iriarte Crom y Erick Teper"))
        self.label_3.setText(_translate("informacion", "Docente: Ing.  Juan Marcelo Barreto Rodriguez"))
        self.label_4.setText(_translate("informacion", "Diplomatura en Python, Año: 2022"))
